export { createBoard } from './createBoard'
export { isMoveValid } from './isMoveValid'
export { getKillVariants } from './getKillVariant'
export { makeFigureStain } from './makeFigureStain'
export { changeBoardAfterMove } from './changeBoardAfterMove'
export { killFigureFromBoard } from './killFigureFromBoard'
